name: CMake Build (Linux)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout код
        uses: actions/checkout@v3

      - name: Установка зависимостей
        run: |
          sudo apt update
          sudo apt install -y cmake g++ make

      - name: Сборка через CMake
        run: |
          mkdir build
          cd build
          cmake ..
          make
