name: Build with CMake on Kali Linux and Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-kali-gcc:
    runs-on: ubuntu-latest
    container: kalilinux/kali-rolling
    name: Kali Linux GCC Build

    steps:
      - uses: actions/checkout@v3

      - name: Установка зависимостей
        run: |
          apt update
          apt install -y cmake g++ make build-essential

      - name: Сборка проекта
        run: |
          mkdir build && cd build
          cmake ..
          make

  build-kali-clang:
    runs-on: ubuntu-latest
    container: kalilinux/kali-rolling
    name: Kali Linux Clang Build

    steps:
      - uses: actions/checkout@v3

      - name: Установка зависимостей
        run: |
          apt update
          apt install -y cmake clang make build-essential

      - name: Сборка проекта
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=clang++ ..
          make

  build-windows-msvc:
    runs-on: windows-latest
    name: Windows MSVC Build

    steps:
      - uses: actions/checkout@v3

      - name: Сборка через CMake
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 17 2022" ..
          cmake --build .
